CREATE TABLE USUARIOS (
    CODIGO_USUARIO NUMBER,
    USERNAME VARCHAR2(50) NOT NULL,
    USER_PASSWORD VARCHAR2(50) NOT NULL,
    PRIMARY KEY (ID_USUARIO)
);

INSERT INTO USUARIOS (CODIGO_USUARIO, USERNAME, USER_PASSWORD)
    VALUES (1, 'VERIS', 'PRUEBAS123');

COMMIT;
    

CREATE TABLE DAF_TIPOS_IDENTIFICACION (
    CODIGO_TIPO_IDENTIFICACION NUMBER,
    NOMBRE_TIPO_IDENTIFICACION VARCHAR2(25) NOT NULL,
    ESTADO VARCHAR2(1) CONSTRAINT REVISAR_ESTADO CHECK (ESTADO IN ('S', 'N')) NOT NULL,
    PRIMARY KEY (CODIGO_TIPO_IDENTIFICACION)
);


CREATE SEQUENCE MGM_SEQ_PACIENT
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1;

CREATE TABLE MGM_PACIENTES (
    ID_PACIENTE NUMBER DEFAULT MGM_SEQ_PACIENT.NEXTVAL,
    CODIGO_TIPO_IDENTIFICACION NUMBER NOT NULL,
    NUMERO_IDENTIFICACION VARCHAR2(50) NOT NULL,
    PRIMER_NOMBRE VARCHAR2(50) NOT NULL,
    SEGUNDO_NOMBRE VARCHAR2(50),
    PRIMER_APELLIDO VARCHAR2(50) NOT NULL,
    SEGUNDO_APELLIDO VARCHAR2(50),
    NOMBRE_COMPLETO VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(50) NOT NULL,
    ESTADO VARCHAR2(1) CONSTRAINT REVISAR_ESTADO_P CHECK (ESTADO IN ('S', 'N')) NOT NULL,
    FECHA_INGRESO DATE NOT NULL,
    USUARIO_INGRESO VARCHAR2(25) NOT NULL,
    FECHA_MODIFICACION DATE,
    USUARIO_MODIFICACION VARCHAR2(25),
    
    PRIMARY KEY (ID_PACIENTE),
    CONSTRAINT FK_TIPO_IDENTIFICACION FOREIGN KEY (CODIGO_TIPO_IDENTIFICACION) REFERENCES DAF_TIPOS_IDENTIFICACION(CODIGO_TIPO_IDENTIFICACION)
);



INSERT INTO DAF_TIPOS_IDENTIFICACION (CODIGO_TIPO_IDENTIFICACION, NOMBRE_TIPO_IDENTIFICACION, ESTADO)
    VALUES (1, 'CEDULA', 'S');
    
INSERT INTO DAF_TIPOS_IDENTIFICACION (CODIGO_TIPO_IDENTIFICACION, NOMBRE_TIPO_IDENTIFICACION, ESTADO)
    VALUES (2, 'RUC', 'S');
    
INSERT INTO DAF_TIPOS_IDENTIFICACION (CODIGO_TIPO_IDENTIFICACION, NOMBRE_TIPO_IDENTIFICACION, ESTADO)
    VALUES (3, 'PASAPORTE', 'S');
    
COMMIT;



INSERT INTO MGM_PACIENTES (ID_PACIENTE, CODIGO_TIPO_IDENTIFICACION, NUMERO_IDENTIFICACION, PRIMER_NOMBRE, SEGUNDO_NOMBRE, 
    PRIMER_APELLIDO, SEGUNDO_APELLIDO, NOMBRE_COMPLETO, EMAIL, ESTADO, FECHA_INGRESO, USUARIO_INGRESO)
    VALUES
    (1, 1, '1044422199', 'Jairo', 'Enrique', 'Aquite', 'Ramirez', 'Jairo Enrique Aquite Ramires', 
        'aquite@gmail.com', 'S', SYSDATE, 'JAQUITE');
    
INSERT INTO MGM_PACIENTES (ID_PACIENTE, CODIGO_TIPO_IDENTIFICACION, NUMERO_IDENTIFICACION, PRIMER_NOMBRE, SEGUNDO_NOMBRE, 
    PRIMER_APELLIDO, SEGUNDO_APELLIDO, NOMBRE_COMPLETO, EMAIL, ESTADO, FECHA_INGRESO, USUARIO_INGRESO)
    VALUES
    (2, 1, '8545213011', 'Jose', 'Manuel', 'Avedano', 'Saltaren', 'Jose Manuel Avedano Saltaren', 
        'avedano@gmail.com', 'S', SYSDATE, 'AVEDANO');
        
INSERT INTO MGM_PACIENTES (ID_PACIENTE, CODIGO_TIPO_IDENTIFICACION, NUMERO_IDENTIFICACION, PRIMER_NOMBRE, SEGUNDO_NOMBRE, 
    PRIMER_APELLIDO, SEGUNDO_APELLIDO, NOMBRE_COMPLETO, EMAIL, ESTADO, FECHA_INGRESO, USUARIO_INGRESO)
    VALUES
    (3, 2, '1129583111', 'Juan', 'Manuel', 'Serje', 'Barreto', 'Juan Manuel Serje Barreto', 
        'manuel@gmail.com', 'S', SYSDATE, 'SERJE');
        
INSERT INTO MGM_PACIENTES (ID_PACIENTE, CODIGO_TIPO_IDENTIFICACION, NUMERO_IDENTIFICACION, PRIMER_NOMBRE, SEGUNDO_NOMBRE, 
    PRIMER_APELLIDO, SEGUNDO_APELLIDO, NOMBRE_COMPLETO, EMAIL, ESTADO, FECHA_INGRESO, USUARIO_INGRESO)
    VALUES
    (4, 2, '1140816752', 'Cesar', 'Andres', 'Arroyo', 'Barrios', 'Cesar Andres Arroyo Barrios', 
        'barrios@gmail.com', 'S', SYSDATE, 'BARRANDRES');
        
INSERT INTO MGM_PACIENTES (ID_PACIENTE, CODIGO_TIPO_IDENTIFICACION, NUMERO_IDENTIFICACION, PRIMER_NOMBRE, SEGUNDO_NOMBRE, 
    PRIMER_APELLIDO, SEGUNDO_APELLIDO, NOMBRE_COMPLETO, EMAIL, ESTADO, FECHA_INGRESO, USUARIO_INGRESO)
    VALUES
    (5, 3, '1045684960', 'Maria', 'Alejandra', 'Reyes', 'Reyes', 'Maria Alejandra Reyes Reyes', 
        'reyesx2@gmail.com', 'S', SYSDATE, 'MARIALE');
        
INSERT INTO MGM_PACIENTES (ID_PACIENTE, CODIGO_TIPO_IDENTIFICACION, NUMERO_IDENTIFICACION, PRIMER_NOMBRE, SEGUNDO_NOMBRE, 
    PRIMER_APELLIDO, SEGUNDO_APELLIDO, NOMBRE_COMPLETO, EMAIL, ESTADO, FECHA_INGRESO, USUARIO_INGRESO)
    VALUES
    (6, 2, '1045669524', 'Jorge', 'Antonio', 'Guillermo', 'Toro', 'Jorge Antonio Guillermo Toro', 
        'guillermo@gmail.com', 'S', SYSDATE, 'TORO');
        
INSERT INTO MGM_PACIENTES (ID_PACIENTE, CODIGO_TIPO_IDENTIFICACION, NUMERO_IDENTIFICACION, PRIMER_NOMBRE, SEGUNDO_NOMBRE, 
    PRIMER_APELLIDO, SEGUNDO_APELLIDO, NOMBRE_COMPLETO, EMAIL, ESTADO, FECHA_INGRESO, USUARIO_INGRESO)
    VALUES
    (7, 1, '1140825190', 'Jorge', 'Alberto', 'Comas', 'Molina', 'Jorge Alberto Comas Molina', 
        'comas@outlook.com', 'S', SYSDATE, 'COMAS');
        
INSERT INTO MGM_PACIENTES (ID_PACIENTE, CODIGO_TIPO_IDENTIFICACION, NUMERO_IDENTIFICACION, PRIMER_NOMBRE, SEGUNDO_NOMBRE, 
    PRIMER_APELLIDO, SEGUNDO_APELLIDO, NOMBRE_COMPLETO, EMAIL, ESTADO, FECHA_INGRESO, USUARIO_INGRESO)
    VALUES
    (8, 2, '1045673983', 'Luz', 'Hansel', 'Salado', 'Castro', 'Luz Hansel Salado Castro', 
        'salado@gmail.com', 'S', SYSDATE, 'SALCASTRO');
        
INSERT INTO MGM_PACIENTES (ID_PACIENTE, CODIGO_TIPO_IDENTIFICACION, NUMERO_IDENTIFICACION, PRIMER_NOMBRE, SEGUNDO_NOMBRE, 
    PRIMER_APELLIDO, SEGUNDO_APELLIDO, NOMBRE_COMPLETO, EMAIL, ESTADO, FECHA_INGRESO, USUARIO_INGRESO)
    VALUES
    (9, 3, '1045674325', 'Carmen', 'Mercedes', 'Salazar', 'Suarez', 'Carmen Mercedes Salazar Suarez', 
        'carmen@gmail.com', 'S', SYSDATE, 'SUAREZCAR');
        
INSERT INTO MGM_PACIENTES (ID_PACIENTE, CODIGO_TIPO_IDENTIFICACION, NUMERO_IDENTIFICACION, PRIMER_NOMBRE, SEGUNDO_NOMBRE, 
    PRIMER_APELLIDO, SEGUNDO_APELLIDO, NOMBRE_COMPLETO, EMAIL, ESTADO, FECHA_INGRESO, USUARIO_INGRESO)
    VALUES
    (10, 2, '1047337358', 'Pablo', 'Luis', 'Escobar', 'Garavito', 'Pablo Luis Escobar Garavito', 
        'garavito@hotmail.com', 'S', SYSDATE, 'ESCOBA');

COMMIT;


SELECT * FROM DAF_TIPOS_IDENTIFICACION;
SELECT * FROM MGM_PACIENTES;
        
        
        
        
        
